# Generated by Django 2.2.5 on 2019-09-19 14:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expanded_user', '0002_auto_20190919_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='userCountry',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
