# Generated by Django 2.2.5 on 2019-10-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expanded_user', '0004_auto_20191012_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='userTimeZone',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
