LOGGING = {
	'version':1,
	'disable_existing_loggers': False,
	'formatters':{
		'large':{
			'format':'%(asctime)s  %(levelname)s  %(process)d  %(pathname)s  %(funcName)s  %(lineno)d  %(message)s  '
		},
		'tiny':{
			'format':'%(asctime)s  %(message)s  '
		}
	},
	'handlers':{
		'errors_file':{
			'level':'ERROR',
		       'class':'logging.handlers.TimedRotatingFileHandler',
			'when':'midnight',
			'interval':1,
			'filename':'logs/ErrorLoggers.log',
			'formatter':'large',
		},
		'info_file':{
			'level':'INFO',
		       'class':'logging.handlers.TimedRotatingFileHandler',
			'when':'midnight',
			'interval':1,
			'filename':'logs/InfoLoggers.log',
			'formatter':'large',
		},
		'darksky_info_file':{
			'level':'INFO',
		       'class':'logging.handlers.TimedRotatingFileHandler',
			'when':'midnight',
			'interval':1,
			'filename':'logs/DarkSkyInfoLoggers.log',
			'formatter':'large',
		},
		'darksky_error_file':{
			'level':'ERROR',
		       'class':'logging.handlers.TimedRotatingFileHandler',
			'when':'midnight',
			'interval':1,
			'filename':'logs/DarkSkyErrorLoggers.log',
			'formatter':'large',
		},
		'rechaptcha_info_file':{
			'level':'INFO',
		   	'class':'logging.handlers.TimedRotatingFileHandler',
			'when':'midnight',
			'interval':1,
			'filename':'logs/reChaptchaInfoLoggers.log',
			'formatter':'large',
		},
		'rechaptcha_error_file':{
			'level':'ERROR',
		       'class':'logging.handlers.TimedRotatingFileHandler',
			'when':'midnight',
			'interval':1,
			'filename':'logs/reChaptchaErrorLoggers.log',
			'formatter':'large',
		},
		'locationiq_info_file':{
			'level':'INFO',
		   	'class':'logging.handlers.TimedRotatingFileHandler',
			'when':'midnight',
			'interval':1,
			'filename':'logs/locationiqInfoLoggers.log',
			'formatter':'large',
		},
		'locationiq_error_file':{
			'level':'ERROR',
		       'class':'logging.handlers.TimedRotatingFileHandler',
			'when':'midnight',
			'interval':1,
			'filename':'logs/locationiqErrorLoggers.log',
			'formatter':'large',
		},
	},
	'loggers':{
		'error_logger':{
			'handlers':['errors_file'],
			'level':'WARNING',
			'propagate':False,
		},
		'info_logger':{
			'handlers':['info_file'],
			'level':'INFO',
			'propagate':False,
		},
		'darksky_info_logger':{
			'handlers':['darksky_info_file'],
			'level':'INFO',
			'propagate':False,
		},
		'darksky_error_logger':{
			'handlers':['darksky_error_file'],
			'level':'ERROR',
			'propagate':False,
		},
		'rechaptcha_info_logger':{
			'handlers':['rechaptcha_info_file'],
			'level':'INFO',
			'propagate':False,
		},
		'rechaptcha_error_logger':{
			'handlers':['rechaptcha_error_file'],
			'level':'ERROR',
			'propagate':False,
		},

		'locationiq_info_logger':{
			'handlers':['locationiq_info_file'],
			'level':'INFO',
			'propagate':False,
		},
		'locationiq_error_logger':{
			'handlers':['locationiq_error_file'],
			'level':'ERROR',
			'propagate':False,
		},
	},
}