# Generated by Django 2.2.5 on 2019-11-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='default_cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stockholm', models.CharField(blank=True, max_length=50, null=True)),
                ('Tokyo', models.CharField(blank=True, max_length=50, null=True)),
                ('New_York', models.CharField(blank=True, max_length=50, null=True)),
                ('Moscow', models.CharField(blank=True, max_length=50, null=True)),
                ('Berlin', models.CharField(blank=True, max_length=50, null=True)),
                ('Paris', models.CharField(blank=True, max_length=50, null=True)),
                ('Bejing', models.CharField(blank=True, max_length=50, null=True)),
                ('Rome', models.CharField(blank=True, max_length=50, null=True)),
                ('San_Francisco', models.CharField(blank=True, max_length=50, null=True)),
                ('Split', models.CharField(blank=True, max_length=50, null=True)),
                ('London', models.CharField(blank=True, max_length=50, null=True)),
                ('Shanghai', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
