# Generated by Django 2.2.5 on 2019-12-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_cities',
            name='weatherIconDesc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
