# Generated by Django 2.2.5 on 2019-09-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_phone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_phone',
            old_name='wantsToReceiveWeatherSMS',
            new_name='wantsToReceiveWeatherSMS',
        ),
    ]
